create table bokqueaf
(
dbkqumes    char(20),
bkrebook    decimal(8,0),
bkreurno    char(8),
bkreadoc    char(6),
bkresdoc    char(6),
bkreedat    char(8),
bkreatim    char(8),
bkrepdat    char(8),
bkreptim    char(8),
bkreadat    char(8),
bkretype    char(3),
bkrecanc    char(3),
bkreomem    char(1),
bkreprev    char(1),
bkreaccm    char(3),
bkreproc    char(9),
bkrecnt     decimal(2,0),
bkreward    char(3),
bkreadmn    decimal(8,0),
bkreprea    char(1),
bkreebed    char(3),
bkreclss    char(3),
bkreatyp    char(3),
bkredept    char(3),
bkretdoc    char(6),
bkreclmt    char(3),
bkrerfgp    char(8),
bkregppc    char(6),
bkregpfa    char(20),
bkreresi    char(3),
bkreeaty    char(3),
bkreecra    char(20),
bkregppt    char(2),
bkredofr    char(3),
bkreoper    char(4),
bkreelos    decimal(3,0),
bkrebkdt    char(8),
bkrxpowd    char(3),
bkrxadwd    char(3),
bkrxcdte    char(8),
bkrxpsty    char(1),
bkrxcndt    char(8),
bkrxudf1    char(3),
bkrxudf2    char(3),
bkrxudf3    char(3),
bkrxudf4    char(3),
bkrxudf5    char(3),
bkrxudd1    char(8),
bkrxudd2    char(8),
bkrxudd3    char(8),
bkrxudd4    char(8),
bkrxuff1    char(50),
bkrxuff2    char(50),
bkrxuff3    char(50),
bkrxuff4    char(50),
bkrxedc1    char(10),
bkrxedc2    char(10),
bkrxedc3    char(10),
bkrxodte    char(8),
bkrxoprd    char(3),
bkquspar    char(71),
lf          char(1)
);
create unique index bokquea1 on bokqueaf
(
dbkqumes
);
revoke all on bokqueaf from public ; 
grant select on bokqueaf to public ; 
